name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.8"]
        arch: [amd64, ppc64le]
        without_extension: ["0", "1"]
        exclude:
          - arch: ppc64le
            os: ubuntu-latest # GitHub-hosted runners only support x64; self-hosted needed for ppc64le

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        architecture: ${{ matrix.arch == 'amd64' && 'x64' || matrix.arch }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install coveralls pytest
        python setup.py develop

    - name: Run tests
      env:
        WITHOUT_EXTENSION: ${{ matrix.without_extension }}
      run: |
        coverage run --source=mwparserfromhell -m pytest

    - name: Upload to Coveralls
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        coveralls

